### get cart

GET http://localhost:8080/cart/

### get cart by id

GET http://localhost:8080/cart/

### create a new cart

POST http://localhost:8080/cart
Content-Type: application/json

{
  "userId": "67088d31f15c8707c334e880",
  "eventIds": [],
  "totalPrice": 0
}

### Update a cart

PUT http://localhost:8080/cart/67085c2ab7a6f424903adeea
Content-Type: application/json

{
    "id": "67088f30f15c8707c334e883",
    "userId": "67088d31f15c8707c334e880",
    "eventIds": [],
    "totalPrice": 10
}

### clear a cart

POST http://localhost:8080/cart/clear/67088f30f15c8707c334e883

### delete cart

DELETE http://localhost:8080/cart/67088f30f15c8707c334e883
