### Get Users

GET http://localhost:8080/users

### Get User by Id

GET http://localhost:8080/users/67088df4f15c8707c334e882

### Get User by Username

GET http://localhost:8080/users/username/camilo

### Get User by Email

GET http://localhost:8080/users/email/camiloesteban661@gmail.com

### Create a new user

POST http://localhost:8080/users
Content-Type: application/json

{
  "role": "user",
  "firstname": "John",
  "lastname": "Doe",
  "username": "Jhon",
  "address": "miami",
  "email": "camiloesteban661@gmail.com",
  "password": "123456",
  "dateOfBirth": "1990-01-01",
}

### Update a user

PUT http://localhost:8080/users/670840b39ab6de65663035fd
Content-Type: application/json

{
  "id": "67088df4f15c8707c334e882",
  "role": "USER",
  "username": null,
  "firstname": "John",
  "lastname": "Doe",
  "address": "miami",
  "email": "camiloesteban661@gmail.com",
  "password": "123456",
  "dateOfBirth": "1990-01-01",
  "cartId": null,
  "phoneNumbers": ["123", "456"],
  "purchases": [],
  "coupons": [],
  "active": true
}

### Delete a user

DELETE http://localhost:8080/users/67088df4f15c8707c334e882
